### ISSUE TITLE
Multiple mailcow.conf

### ISSUE THREAD

**Issue by hockeymikey** [asifbacchus/MailcowBackup#2]
The script bugs out trying to find the mailcow.conf since I had an apache site conf called mailcow.conf. I couldn't override the path either explicitly with an argument either. Something to look in to. I just renamed the site, but may be good for others

**Comment by asifbacchus** [comment]
I just assumed that people would keep as 'default' a setup as possible and I personally always number my vserver files to control load order (i.e. 10-mailcow.conf).  But, I like your suggestion. I'll review the suggested code later today when I have a few minutes.  Thanks!  Nice catch :-)

**Comment by hockeymikey** [comment]
Anytime! My pull request doesn't fix this issue, but I don't think a fix would be too complex.

**Comment by asifbacchus** [comment]
I'm likely redoing this script this weekend (I hope) to make it POSIX compliant instead of using BASH so it can be used by people on more systems. I think I'll replace the automatic path search for the mailcow.conf file entirely with parameter input.  Right now, the script only allows you to search for a differently named file.  I'll change that to requiring the parameter to specify a full path.

If I don't get around to completely re-writing the script this weekend, I'll implement the change in this (BASH) version and do a new release.  Thanks again @hockeymikey for pointing this out!

Oh, and I'll merge you commit in the meantime also since it's a great addition to the script that I'm totally stealing and putting into the new version.  I just have to figure out how to sync the change with my actual private server I use and not just here on github.

**Comment by asifbacchus** [comment]
* merge to take care of non-standard container names (commit fb8091e)
* remove auto-searching for 'mailcow.conf' and require user provide full path via '-m' script parameter (commit bbbdf38)

These fixes are in the v1.6 release.

**Comment by hockeymikey** [comment]
Any time, glad to hear. Thanks for creating such a great project, just happy to help.
