### ISSUE TITLE
How to backup to local folder

### ISSUE THREAD

**Issue by makuip** [asifbacchus/MailcowBackup#8]
Hi,

I can't access my backup space using ssh. Therefore, I plan to backup to a local folder and use ftps to mirror this folder to my backup space.

How can I configure a backup to a local folder?

Thanks,

Martin

**Comment by asifbacchus** [comment]
Hey Martin!

You can actually get more details about this in the borg documentation since this script really is just a wrapper for that program. However, I'll try to give you a simple explanation here also:

To backup locally, you specify a borg repo location *without* and **@** sign. So, when you are making your repo you would use something like:

```bash
# create repo
borg init -e keyfile-blake2 /var/backup/myEmailBackup

# export key for backup purposes
borg key export /var/backup/myEmailBackup /home/martin/myEmailBackup.borg.key
```

In this example, I created a repo that is stored locally at `/var/backup/myEmailBackup` and then exported the encryption key to the user's home directory. If you create a *repokey* type repository, exporting is not necessary and you only have to remember the password. That's beyond the scope of your question and the borg documentation covers the differences nicely.

Ok, you have a local repo! Now we can use it. In your *backup.details* file, set everything up per the examples/documentation, except for the following items:

- `borgSSHKey`: point this to a dummy file since you will not be using it. The script checks for this file though, so it must still exist. You might just do something like `touch /var/borgbackup/dummy.key` to create an empty file and use that file as the value for this variable.
- `borgConnectRepo`: this is the important setting. Just set it to (using our example above) `/var/backup/myEmailBackup`. Because it does not have an *@* sign, borg will know it's local and will disregard the settings for SSH key, etc.

Everything else should be the same whether you are using a remote or a local backup. Sorry, I wrote the documentation and stuff just assuming a remote backup location.

Let me know if this works, if you have any problems, or if you need any more help!

**Comment by makuip** [comment]
Hi Asif!

Thanks a lot for your quick response and detailed instructions. 

With this help I could make it working. I had never used borg before and I'm surprised how lightning fast it is.

Martin

**Comment by asifbacchus** [comment]
Yup, the speed of borg is why I started using it and wrote the script in the first place. It's a pretty great piece of software.

Anyways, I'm glad you got everything sorted out! Feel free to open another issue if you run into any other problems or need any more help.

All the best :smile:
